### ISSUE TITLE
In version v0.10.0 the tests are failing: FAIL: TestGenerateTextRandomData

### ISSUE THREAD

**Issue by Silenke2x2** [logdyhq/logdy-core#18]
Hi. I am downloading the latest version 0.10.0 from Github and trying to run the tests: **# go test -v ./...**
I am getting an error:
```
=== RUN TestGenerateTextRandomData
--- FAIL: TestGenerateTextRandomData (0.00s)
panic: slice is empty [recovered]
panic: slice is empty

goroutine 6 [running]:
testing.tRunner.func1.2({0x783d60, 0x8cdb20})
/usr/lib/golang/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
/usr/lib/golang/src/testing/testing.go:1634 +0x377
panic({0x783d60?, 0x8cdb20?})
/usr/lib/golang/src/runtime/panic.go:770 +0x132
logdy/utils.PickRandom[...](...)
/root/test/logdy-core/utils/utils.go:53
logdy/modes.generateTextRandomData()
/root/test/logdy-core/modes/demo.go:86 +0x427
logdy/modes.TestGenerateTextRandomData(0xc000185380)
/root/test/logdy-core/modes/demo_test.go:13 +0x18
testing.tRunner(0xc000185380, 0x868da8)
/usr/lib/golang/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
/usr/lib/golang/src/testing/testing.go:1742 +0x390
FAIL logdy/modes 0.013s
```

P.S. All tests passed successfully in version 0.9.0

**Comment by Silenke2x2** [comment]
After updating to version 0.11.0: **# go test -v ./...**
```
--- FAIL: TestConsumeStdinAndForwardToPort (0.00s)
panic: dial tcp :8123: connect: connection refused [recovered]
        panic: dial tcp :8123: connect: connection refused

goroutine 26 [running]:
testing.tRunner.func1.2({0x7b8100, 0xc0002a4a50})
        /usr/lib/golang/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
        /usr/lib/golang/src/testing/testing.go:1634 +0x377
panic({0x7b8100?, 0xc0002a4a50?})
        /usr/lib/golang/src/runtime/panic.go:770 +0x132
logdy/modes.ConsumeStdinAndForwardToPort({0x0, 0x0}, {0x8015e1, 0x4})
        /root/logdy-core/modes/forward.go:20 +0x496
logdy/modes.TestConsumeStdinAndForwardToPort(0xc0002ce1a0)
        /root/logdy-core/modes/forward_test.go:53 +0x149
testing.tRunner(0xc0002ce1a0, 0x86efb0)
        /usr/lib/golang/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
        /usr/lib/golang/src/testing/testing.go:1742 +0x390
FAIL    logdy/modes     0.216s
```
This bug was not present in version 0.9.0 and 0.10.0
p.s my port 8123 is free
